/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/hello-my-friends-9c20a10f2352406fa90485fafc531fa9
Title: Hello my friends
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0.002, -34.848, -3.351]} rotation={[Math.PI / 2, 0, 0.001]} scale={0.016}>
          <group name="71befc7a795942eda13c8625345d5dbbfbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" position={[-19.158, -1.254, 4.843]} rotation={[0, Math.PI / 2, 0]} scale={[0.558, 0.558, 1]} />
                  <group name="Object_8" position={[-19.158, -1.254, 4.843]} rotation={[0, Math.PI / 2, 0]} scale={[0.558, 0.558, 1]} />
                  <group name="hahmo" position={[-0.232, -1.16, 0]}>
                    <mesh name="hahmo_01_-_Default_0" geometry={nodes['hahmo_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  </group>
                  <group name="silm��t" position={[-6.235, -10.221, 8.234]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh name="silm��t_03_-_Default_0" geometry={nodes['silm��t_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  </group>
                  <group name="jalat" position={[-4.323, -1.254, -4.638]} scale={[0.9, 0.9, 1]}>
                    <mesh name="jalat_07_-_Default_0" geometry={nodes['jalat_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  </group>
                  <group name="Cylinder004" position={[0.165, -1.675, -5.125]}>
                    <mesh name="Cylinder004_08_-_Default_0" geometry={nodes['Cylinder004_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                  </group>
                  <group name="k��det" position={[-14.141, -1.254, 6.207]} rotation={[0, Math.PI / 2, 0]} scale={[0.558, 0.558, 1]} />
                  <group name="Plane001" position={[21.576, 0, 24.973]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh name="Plane001_02_-_Default_0" geometry={nodes['Plane001_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                  </group>
                  <group name="suu" position={[-0.335, -10.898, 5.505]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.244]}>
                    <mesh name="suu_03_-_Default_0" geometry={nodes['suu_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  </group>
                  <group name="k��det_reuna" position={[-14.141, -1.254, 6.207]} rotation={[0, Math.PI / 2, 0]} scale={[0.558, 0.558, 1]} />
                  <group name="hahmo_reunat" position={[-0.232, -1.16, 0]}>
                    <mesh name="hahmo_reunat_09_-_Default_0" geometry={nodes['hahmo_reunat_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  </group>
                  <group name="jalat_reunat" position={[-4.323, -1.254, -4.638]} scale={[0.9, 0.9, 1]}>
                    <mesh name="jalat_reunat_09_-_Default_0" geometry={nodes['jalat_reunat_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  </group>
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['07_-_Default']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['09_-_Default']} skeleton={nodes.Object_9.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
